### ISSUE TITLE
"FileNotFoundError" when use vscode in windows

### ISSUE THREAD

**Issue by yhj050806** [tqchen/ffi-navigator#42]
error log:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\ffi_navigator\langserver.py", line 62, in m_text_document__definition
    source = open(path).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'c%3A\\work\\file\\technicial_file_record\\TVM\\incubator-tvm-main\\tutorials\\language\\schedule_primitives.py'

**Comment by comaniac** [comment]
@masahi it looks like the path issue on Windows?

**Comment by masahi** [comment]
Yeah, `%3` seems like a space? I don't have access to windows at the moment.

**Comment by saurabh-shandilya** [comment]
@lygztq 
I encountered similar error, so tried installing from source but now I get a different error 

"UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2228: character maps to <undefined>"

My environment setting
Windows 11. 
VSCode 1.69.2 - VSCode extension downloaded and installed via marketplace
Python  3.7- ffi-navigator installed via build from source version ffi-navigator==0.5.3 (Anaconda)

**Comment by SStarver** [comment]
Help!!!!!  Already been driven crazy~~
 I've encountered the same question in this issue after solving several  other installing problems

![image](https://user-images.githubusercontent.com/108868933/187431609-2255170d-b835-4f54-ba23-e7706f5ce7dc.png)

**Comment by saurabh-shandilya** [comment]
@tqchen Can you please help?

**Comment by SStarver** [comment]
> @tqchen Can you please help?
Any advices would be much appreciated
This problem significantly  dispels the passion of TVM  beginner like me
